### ISSUE TITLE
No path.txt found

### ISSUE THREAD

**Issue by paulkernfeld** [electron-userland/electron-prebuilt#85] opened 2015-12-29 10:32 UTC
I just ran into a problem trying to build the [patchwork](https://github.com/ssbc/patchwork) project from source, because of an error installing electron-prebuilt (same error as #76):

`Error: ENOENT: no such file or directory, open blah/blah/patchwork/node_modules/electron-prebuilt/path.txt`

When I run electron-prebuilt's `install.js` myself, it correctly downloads the Electron binary and creates `path.txt`. However, this doesn't happen when I run `npm install` from the patchwork directory. Is it possible that there is something preventing electron-prebuilt's postinstall hook from being run in this case?

So far I have tried:
1. Completely zapping all versions of node.js and reinstalling them
2. Completely zapping the patchwork directory and re-cloning it, which has the effect of deleting `node_modules/`

I'm not sure whether this error is on the patchwork side or on the electron-prebuilt side, so I'll happily move the issue if it's in the wrong place.

I am running brew-installed node 5.3.0 and npm 3.3.12 on OSX. Let me know if I can provide any additional information.

**Comment by maxogden** [comment] 2015-12-29 18:26
Hmm weird. You could try `DEBUG=* npm install` and see what the debug logs say, compared to `DEBUG=* node install.js`

**Comment by paulkernfeld** [comment] 2016-01-01 13:38
Sorry, I’m a little confused (Node beginner). Did you mean that I should set the DEBUG environment variable to the string consisting of just an asterisk? That didn’t seem to produce any output, so I think I must be doing the wrong thing.

**Comment by Hugheth** [comment] 2016-01-10 18:16
I also had this problem. Deleting node_modules and running ``npm install`` again fixed it for me - I suspect a partially installed build where path.txt is missing would cause this error

**Comment by maxogden** [comment] 2016-01-10 19:48
@paulkernfeld oops just saw your reply sorry. Yes setting `DEBUG` to `*` should enable all debug logging (http://npmjs.org/debug)

@Hugheth hmm you're probably right, but I'm not sure how to reproduce that state in a test... hmm...

**Comment by darkyen** [comment] 2016-01-17 05:44
Well I had the same problem today, just re-installing it worked. I guess something is eating up the error.

**Comment by jlord** [comment] 2016-06-22 16:40
@paulkernfeld were you able to resolve this issue? I've seen things like this occur due to just a weird install from npm and a re-install, as @darkyen mentioned, usually does the trick.

**Comment by paulkernfeld** [comment] 2016-06-22 18:41
Sorry, this happened a while ago and I don't remember whether or how I was able to resolve it.

**Comment by jlord** [comment] 2016-06-22 19:57
No worries. I'll close it out then 👍

**Closed by jlord** 2016-06-22 19:57 UTC

**Comment by EmrysMyrddin** [comment] 2016-07-19 09:13
This seems to happen when a compilation error occured. If you just try to run `npm install` a second time after having solved the compilation error, `npm install` works but it seems to not run the `install.js` script of electron-prebuilt.

**Comment by zeke** [comment] 2016-07-22 20:05
>  it seems to not run the install.js script

I think you may be right. In this case you should `rm -rf node_modules && npm i` to start anew.

**Comment by EmrysMyrddin** [comment] 2016-07-22 21:20
Yes exactly, reinstalling dependencies résolve the problem.
