### ISSUE TITLE
Install fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by aviaryan** [electron-userland/electron-prebuilt#137] opened 2016-05-21 07:45 UTC
Install fails on Ubuntu 14.04 . There is a phrase ECONNRESET in the trace which gives the impression this may be a connection issue but my computer is always connected to the Internet. 

```
sudo npm install -g electron-prebuilt
[sudo] password for aviaryan: 
/usr/bin/electron -> /usr/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@1.1.1 postinstall /usr/lib/node_modules/electron-prebuilt
> node install.js

Downloading electron-v1.1.1-linux-x64.zip
Error: read ECONNRESET
/usr/lib/node_modules/electron-prebuilt/install.js:22
  throw err
  ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TLSWrap.onread (net.js:552:26)
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "electron-prebuilt"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@1.1.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.1.1 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/aviaryan/npm-debug.log
```

Attached the npm-debug.log below . Please help me fix this issue.

Thanks

[npm-debug.log.tar.gz](https://github.com/electron-userland/electron-prebuilt/files/275756/npm-debug.log.tar.gz)

**Comment by mrvini** [comment] 2016-05-23 23:43
getting same error here

```bash
npm install electron-prebuilt --save-dev
-
> electron-prebuilt@1.1.1 postinstall /home/test/node_modules/electron-prebuilt
> node install.js

/home/test/node_modules/electron-prebuilt/install.js:22
  throw err
  ^

Error: end of central directory record signature not found
    at /home/test/node_modules/electron-prebuilt/node_modules/extract-zip/node_modules/yauzl/index.js:167:14
    at /home/test/node_modules/electron-prebuilt/node_modules/extract-zip/node_modules/yauzl/index.js:473:5
    at /home/test/node_modules/electron-prebuilt/node_modules/extract-zip/node_modules/yauzl/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)
npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "electron-prebuilt" "--save-dev"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@1.1.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.1.1 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/test/npm-debug.log
```

**Comment by johnmuhl** [comment] 2016-05-24 02:19
@aviaryan, @mrvini could you try the [workaround mentioned here](https://github.com/electron-userland/electron-prebuilt/issues/69#issuecomment-164636460) and let us know if that works for you?

**Comment by aviaryan** [comment] 2016-05-24 02:50
@johnmuhl I was able to successfully install electron yesterday so no need. Thanks. I believe my issue had something to do with download speed; when it failed I was getting only around 60 KB/s. After I moved to twice the faster connection, I had no problems.

**Comment by kevinsawicki** [comment] 2016-09-09 20:29
> Error: read ECONNRESET

Closing this out since the error might be caused by local network issues or issues downloading from GitHub which could have been having downtime or an outage when this happened.

**Closed by kevinsawicki** 2016-09-09 20:29 UTC

**Comment by saydulk** [comment] 2017-07-04 22:22
i am also having the same issue. is their any PPA for electron?

root@CLI:~# npm install -g electron-prebuilt
npm WARN deprecated electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
npm ERR! path /usr/bin/electron
npm ERR! code EEXIST
npm ERR! Refusing to delete /usr/bin/electron: ../lib/node_modules/electron/cli.js symlink target is not controlled by npm /usr/bin
npm ERR! File exists: /usr/bin/electron
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-04T22_20_56_769Z-debug.log
root@CLI:~# rm -rf /usr/bin/electron
root@CLI:~# npm install -g electron-prebuilt
npm WARN deprecated electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
/usr/bin/electron -> /usr/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@1.4.13 postinstall /usr/lib/node_modules/electron-prebuilt
> node install.js

/usr/lib/node_modules/electron-prebuilt/install.js:22
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/electron-prebuilt/.electron'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-prebuilt@1.4.13 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.4.13 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-04T22_21_34_838Z-debug.log
root@CLI:~# sudo npm install -g electron-prebuilt
npm WARN deprecated electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
/usr/bin/electron -> /usr/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@1.4.13 postinstall /usr/lib/node_modules/electron-prebuilt
> node install.js

/usr/lib/node_modules/electron-prebuilt/install.js:22
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/electron-prebuilt/.electron'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-prebuilt@1.4.13 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.4.13 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-04T22_21_55_858Z-debug.log
