### ISSUE TITLE
new "npm install electron" breakpoints problem.

### ISSUE THREAD

**Issue by objectref** [electron-userland/electron-prebuilt#180] opened 2016-08-17 22:41 UTC
Hi,

i was using "npm install electron-prebuilt" and by using "${workspaceRoot}/node_modules/electron-prebuilt/dist/electron.app/Contents/MacOS/Electron" in Visual Studio Code (runtimeExecutable setting) i was able to hit the breakpoints in my javascript code and debug just fine.

But, for a new project i used the new "npm install electron" and thus i changed the command to "${workspaceRoot}/node_modules/electron/dist/electron.app/Contents/MacOS/Electron".

Now, the breakpoints do not get hit. If i change it back to electron-prebuild, they are working fine again. Am i doing something wrong or something is happening with the new electron install command?

**Comment by objectref** [comment] 2016-08-19 14:15
Investigated further, i discovered that it indeed worked correctly (i.e. breakpoints do get hit) with electron-prebuilt v. 1.2.7. I just did a "npm install electron-prebuilt" in a new folder/project, it fetched the 1.3.3 version and breakpoints do not get hit now. Something got broken in 1.3.3... :)

**Comment by kevinsawicki** [comment] 2016-09-09 01:59
I believe this is a duplicate of https://github.com/electron/electron/issues/6608 which was fixed and released in Electron 1.3.5, closing this out here.

**Closed by kevinsawicki** 2016-09-09 01:59 UTC
