### ISSUE TITLE
electron-prebuilt build failed post-install script

### ISSUE THREAD

**Issue by weems** [electron-userland/electron-prebuilt#139] opened 2016-05-25 23:31 UTC
Describe your problem:
"npm ERR! Failed at the electron-prebuilt@1.1.3 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed."
Verbose Log: [electronError.TXT](https://github.com/electron-userland/electron-prebuilt/files/283172/electronError.TXT)

**Comment by gbaumgart** [comment] 2016-05-26 10:33
+1

same here on osx (but not linux/windows)



Downloading electron-v1.1.2-darwin-x64.zip
[============================================>] 100.0% of 41.7 MB (251.59 kB/s)
/usr/local/lib/node_modules/electron-prebuilt/install.js:22
  throw err
        ^
Error: EACCES, rename '/usr/local/lib/node_modules/electron-prebuilt/electron-tmp-download-12959-1464258455971/electron-v1.1.2-darwin-x64.zip'
    at Error (native)
npm info lifecycle electron-prebuilt@1.1.2~postinstall: Failed to exec postinstall script
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "-d" "electron-prebuilt@1.1.2"
npm ERR! node v0.12.7
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@1.1.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@1.1.2 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js

**Comment by mafintosh** [comment] 2016-05-26 10:40
could you try running it with `--unsafe-perm` ? i'm curious if that fixes it

**Comment by gbaumgart** [comment] 2016-05-26 10:42
trying right now, thanks. found the same tip in a similar issue: 

sudo npm install -g electron-prebuilt --unsafe-perm=true --allow-root

**Comment by mafintosh** [comment] 2016-05-26 10:44
if that works we might consider downloading the tmp file in the module directory actually

**Comment by gbaumgart** [comment] 2016-05-26 10:46
yeah, it worked. would be great to see that in the docs, for those who prefer electron being installed globally.

**Comment by PierBover** [comment] 2016-09-06 21:26
I'm having a similar issue on OSX when doing `sudo npm i electron -g`.

```
Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/electron/electron-tmp-download-81810-1473196490319/electron-v1.3.5-darwin-x64.zip' -> '/Users/pier/.electron/electron-v1.3.5-darwin-x64.zip'
```

I've tried with `sudo npm install -g electron --unsafe-perm=true --allow-root` and it worked.

**Comment by PierBover** [comment] 2016-09-06 21:26
I'm having a similar issue on OSX when doing `sudo npm i electron -g`.

```
Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/electron/electron-tmp-download-81810-1473196490319/electron-v1.3.5-darwin-x64.zip' -> '/Users/pier/.electron/electron-v1.3.5-darwin-x64.zip'
```

I've tried with `sudo npm install -g electron --unsafe-perm=true --allow-root` and it worked.

**Comment by zeke** [comment] 2016-10-07 22:22
> downloading the tmp file in the module directory actually

@mafintosh would this need to be added to [electron-download](https://github.com/electron-userland/electron-download)? It looks like the [current (unconfigurable) behavior](http://github.com/electron-userland/electron-download/blob/7f014dfcc2841464199a10e8b5199a89fc0bdd5a/lib/index.js#L152-L158) is to create a directory in `os.tmpdir()`.

Happy to work on a fix for this with a little guidance.

**Comment by mafintosh** [comment] 2016-10-07 23:08
@zeke yea it would. we should try and see if downloading into __dirname fixes the perm issues

**Comment by semanino** [comment] 2016-12-16 11:11
The problem is in package electron-download
file `build/cli.js` uses the deprecated `node` command instead of `nodejs` in its first line which reads `#!/usr/bin/env node`

Choose your favourite solution:
- change the file's first line to read `#!/usr/bin/env nodejs`
- or install a compatibility package in your Linux (on Ubuntu 16.04 LTS this is nodejs-legacy so you would run shell command `sudo apt install nodejs-legacy`)
- or create a symlink named `node` to the `nodejs` executable: use e.g. `which nodejs` to find out where it is; if this returns e.g. `/usr/bin/nodejs`, create the symlink with `sudo ln -s /usr/bin/nodejs /usr/bin/node`

**Comment by mark-jordanovic-lewis** [comment] 2017-07-24 10:12
asdf managed node installs also fail. Assuming due to hard coded interpreter in build/cli.js, got the compressed version and linked it in my path so easy work around but maybe building script from o/p of `which node/nodejs` would fix?

**Comment by Davenchy** [comment] 2017-07-25 17:56
Yes it`s working
`sudo npm install -g electron --unsafe-perm=true --allow-roo`

**Comment by zeke** [comment] 2017-08-08 22:08
The [electron-prebuilt repo is being retired](https://github.com/electron-userland/electron-prebuilt/pull/275) and its code has been moved into the electron/electron repo. For the sake of historical transparency, we will leave GitHub Issues enabled on this repository, but if you are still affected by the issue reported here, please [open a new issue on electron/electron](https://github.com/electron/electron/issues/new) repo and reference this issue from it so people can get the full context. The electron repository has a large and active contributor community, so your issue is more likely to get the attention it deserves there. Thanks!

**Closed by zeke** 2017-08-08 22:08 UTC

**Comment by scripting** [comment] 2017-08-28 14:30
@Davenchy -- thank you -- that worked, nothing else I tried did.

**Comment by Usamaliaquat123** [comment] 2017-11-30 05:19
its working 
`npm install -g electron --unsafe-perm=true --allow-root`
