### ISSUE TITLE
npm install keeps failing with the following error

### ISSUE THREAD

**Issue by paul321** [electron-userland/electron-prebuilt#121] opened 2016-05-03 12:21 UTC
No matter what version of node i try electron-prebuilt keeps reporting this error, now i'm on node 6.0.0

> electron-prebuilt@0.37.6 postinstall C:\Users\Win7\Work\node_modules\electron-prebuilt
> node install.js

module.js:440
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Win7\Work\node_modules\readable-stream\lib\_stream_readable.js:6:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)

**Comment by kevinsawicki** [comment] 2016-09-09 20:26
Closing as a duplicate of https://github.com/electron-userland/electron-prebuilt/issues/63, please subscribe to that issue for updates.

**Closed by kevinsawicki** 2016-09-09 20:26 UTC
