### ISSUE TITLE
Failed at the electron-prebuilt@1.4.10 postinstall script 'node install.js'.

### ISSUE THREAD

**Issue by alexcheninfo** [electron-userland/electron-prebuilt#220] opened 2016-12-02 13:35 UTC
* Electron version: "electron-prebuilt": "1.4.10"
* Operating system: Ubuntu 16.04.1 LTS
* Node version: v7.2.0

I get this error when I try to install `electron-prebuilt`:

```
Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:572:26)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^2.0.2 (node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.0.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules/7zip-bin/node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/home/alex/.nvm/versions/node/v7.2.0/bin/node" "/home/alex/.nvm/versions/node/v7.2.0/bin/npm" "install" "electron-prebuilt@1.4.10"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
```

**Comment by khaledabbas** [comment] 2016-12-04 12:41
getting same error with Windows 10

**Comment by Cedware** [comment] 2016-12-05 09:00
Same on Linux Mint 18 with node 7.2.0

**Comment by nqthiep** [comment] 2016-12-06 09:07
Same on Linux Mint 18 with node 7.2.0 and node 6.9.1

**Comment by nandd** [comment] 2016-12-11 08:21
same on Windows 10 with node 6.9..2 and npm  3.10.9

**Comment by zeke** [comment] 2016-12-12 20:11
`ECONNRESET` is a network error. Installing again should take care of it:

```
npm install electron
```

**Comment by ikitty** [comment] 2016-12-15 15:27
Same on Mac yosemite with node 6.92 and npm 4.x

> ECONNRESET is a network error. Installing again should take care of it:

@zeke how to understand "network error " ?  so much people found this issue . people's network error ?or electron backend service network error ? what I care is how to Fix it .

**Comment by ikitty** [comment] 2016-12-15 15:29
Electron is Amazing! 
but I can not write a simple HelloWorld. cause I cannot install it . Ahh...

**Comment by zeke** [comment] 2016-12-15 19:46
@ikitty sorry you're having trouble. Please provide your operating system, node version, and the output you're seeing when you try to install electron.

**Comment by ikitty** [comment] 2016-12-16 02:38
os: Mac yosemite
node:6.9.2
npm: 4.0.5

here are all info:
```
electron-quick-start [master●] % sudo npm i electron-prebuilt -g
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@1.4.12 postinstall /usr/local/lib/node_modules/electron-prebuilt
> node install.js

/usr/local/lib/node_modules/electron-prebuilt/install.js:22
  throw err
  ^

Error: EACCES: permission denied, link '/usr/local/lib/node_modules/electron-prebuilt/electron-tmp-download-22952-1481855062873/electron-v1.4.12-darwin-x64.zip' -> '/Users/Kty/.electron/electron-v1.4.12-darwin-x64.zip'
    at Error (native)
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "electron-prebuilt" "-g"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@1.4.12 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.4.12 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.
```


"/usr/local/lib/node_modules/electron-prebuilt/electron-tmp-download-22952-1481855062873/electron-v1.4.12-darwin-x64.zip" , I checked this folder, the electron-prebuild folder is not exist in node_modules.

**Comment by zeke** [comment] 2016-12-16 05:21
Give this a try:

```
sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
```

via https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by ikitty** [comment] 2016-12-16 08:05
@zeke 
Just now I use another package manager to install it successfully. the tool is [cnpm](https://www.npmjs.com/package/cnpm)

I will try your sulotion later . thank u all the same.

**Comment by kevinsawicki** [comment] 2016-12-27 22:46
This looks like a duplicate of #212 (`ECONNRESET`) errors, closing this out.

If you are still experiencing this, please confirm whether you are able to download directly from https://github.com/electron/electron/releases as that is the location where the npm package downloads from.

**Closed by kevinsawicki** 2016-12-27 22:46 UTC
