### ISSUE TITLE
Error: Cannot find module './formats/auto'

### ISSUE THREAD

**Issue by tomprogers** [electron-userland/electron-prebuilt#93] opened 2016-02-03 20:46 UTC
This error is thrown when running `npm install` for a project that depends on electron-prebuilt.

Here's the line from package.json:

```
"electron-prebuilt": "^0.36.4",
```

Here's the output during install:

```
[Wed 14:39:39] xde $ npm i

> electron-prebuilt@0.36.4 postinstall /Users/tom/projects/xde/node_modules/electron-prebuilt
> node install.js

module.js:328
    throw err;
    ^

Error: Cannot find module './formats/auto'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/tom/projects/xde/node_modules/sshpk/lib/private-key.js:28:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

**Comment by tomprogers** [comment] 2016-02-03 21:09
Note that this happens 100% of the time when installing electron-prebuilt for the first time.

If I then re-run `npm i`, installation _often_ succeeds. However, at runtime, electron-prebuilt throws an error that breaks my app. I assume that problem is driven by this one -- but even if it isn't, it seems that there's an issue in this project that ought to be addressed.

**Comment by mafintosh** [comment] 2016-02-03 21:31
Which version on npm are you using?

**Comment by tomprogers** [comment] 2016-02-03 21:49
MacOS `10.11.3`
npm `2.14.12`
node `4.2.6`

**Comment by raybooysen** [comment] 2016-03-29 11:51
I'm seeing this today too on Ubuntu:

```
npm -v
2.14.20
node -v
v4.4.1
```

**Comment by kevinsawicki** [comment] 2016-09-09 22:02
@tomprogers @raybooysen are you able to reproduce this using npm 3?

**Comment by raybooysen** [comment] 2016-09-10 08:26
@kevinsawicki no, I've not had it for ages now on npm3 and node 5

**Comment by kevinsawicki** [comment] 2016-09-12 21:45
>  no, I've not had it for ages now on npm3 and node 5

Great to know, this looks like an issue with certain versions of npm 2, closing this out as the workaround is to use npm 3.

**Closed by kevinsawicki** 2016-09-12 21:45 UTC
Labels: more-information-needed
